---
name: ci gha lint

"on":
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  push:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"

jobs:
  gha-lint:
    permissions:
      contents: read
      checks: write
      pull-requests: write
    uses: ./.github/workflows/wf-reviewdog-gha-lint.yaml
    with:
      toolset: all
      reporter: github-pr-review
      filter_mode: added
    secrets:
      github_token: ${{ github.token }}
